name: Publish npm package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v3.0.1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
